name: Upload Api Dashboard

on:
  push:
    branches:
    - nodeSimple

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: NPM clean install
        run: npm ci

      - name: Change to Serverless directory
        run: cd path/to/serverless/project

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ATLAS_SERVER: ${{ secrets.ATLAS_SERVER }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
